---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "auto-abuse-id"
  namespace: "abuse-api-dev"
  labels:
    app: "auto-abuse-id"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "auto-abuse-id"
  template:
    metadata:
      labels:
        app: "auto-abuse-id"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "auto-abuse-id"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/auto_abuse_id:dev"
          livenessProbe:
            httpGet:
              path: /classify/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: dev
          - name: REDIS
            value: auto-abuse-id-cache.abuse-api-dev.svc.cluster.local
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-auto-abuse-id
                key: password
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-auto-abuse-id
                key: password
