---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auto-abuse-id
  namespace: abuse-api-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - classify.int.dev-godaddy.com
      secretName: tls-auto-abuse-id
    - hosts:
      - classify.cset.int.dev-gdcorp.tools
      secretName: cset-wildcard
  rules:
  - host: classify.int.dev-godaddy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auto-abuse-id
            port:
              number: 5000
  - host: classify.cset.int.dev-gdcorp.tools
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auto-abuse-id
            port:
              number: 5000
