---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "auto-abuse-id"
  namespace: "abuse-api-prod"
  labels:
    app: "auto-abuse-id"
spec:
  replicas: 3
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: "auto-abuse-id"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "auto-abuse-id"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/auto_abuse_id:REPLACE_WITH_GIT_COMMIT"
          livenessProbe:
            httpGet:
              path: /classify/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: prod
          - name: KEYFILE
            value: /keyfiles/key.txt
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-auto-abuse-id
                key: password
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-auto-abuse-id
                key: password

          volumeMounts:
          - name: encryption-keys
            mountPath: /keyfiles
            readOnly: true

      volumes:
        - name: encryption-keys
          secret:
            secretName: encryption-key-files
