---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "auto_abuse_id"
  namespace: "abuse-api-ote"
  labels:
    app: "auto_abuse_id"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: "auto_abuse_id"
    spec:
      imagePullSecrets:
        -
          name: "k8s-artifactory-creds"
      containers:
        -
          name: "auto_abuse_id"
          imagePullPolicy: "Always"
          image: "artifactory.secureserver.net:10014/docker-dcu-local/auto_abuse_id:ote"
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: ote
          - name: KEYFILE
            value: /keyfiles/key.txt
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-auto_abuse_id
                key: password

          volumeMounts:
          - name: encryption-keys
            mountPath: /keyfiles
            readOnly: true

      volumes:
        - name: encryption-keys
          secret:
            secretName: encryption-key-files
