apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- auto_abuse_id.ingress.yaml

namespace: abuse-api-ote
images:
- name: docker-dcu-local.artifactory.secureserver.net/auto_abuse_id
  newTag: ote

configMapGenerator:
- literals:
  - sysenv=ote
  - REDIS=auto-abuse-id-cache.abuse-api-ote.svc.cluster.local
  name: env-specific-values
